name: Metrics
on:
  push:
    paths:
      - '.github/workflows/metrics.yml' # monitor the main workflow script.
  schedule:
    - cron: "10,45 4,20 * * *"
  workflow_dispatch: null
jobs:
  github-metrics:
    name: Generate GitHub Metrics for README
    runs-on: oreo
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}

          user: YaoYinYing
          commits_authoring: YaoYinYing, ${{ secrets.AUTHOR_EMAILS }}
          config_timezone: Asia/Shanghai
          template: classic
          repositories: 1000
          repositories_batch: 2
          repositories_affiliations: owner, collaborator, organization_member
          config_order: base.header, base.activity+community, isocalendar, habits, languages, notable, followup, reactions, stargazers

          base: header, activity
          base_indepth: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_facts: no
          plugin_habits_charts: yes

          plugin_languages: yes
          plugin_languages_skipped: BayesWitnesses/m2cgen
          plugin_languages_details: percentage, lines
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_categories: programming

          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_repositories: no
          plugin_notable_types: commit, pull_request, issue

          plugin_followup: yes
          plugin_followup_sections: user
          plugin_followup_indepth: yes

          plugin_reactions: yes
          plugin_reactions_limit: 1000
          plugin_reactions_limit_issues: 1000
          plugin_reactions_display: absolute
          plugin_reactions_details: count

          plugin_stargazers: yes
